#!/bin/bash

cd $(dirname $0)

export PATH="$PWD:$PATH"

launch () {
  ${@} &
}

feh --bg-scale $PWD/../wallpapers/decay.png
pkill picom; picom -b
pkill widgets; launch widgets

cd $HOME

if ! eww ping 2>&1 > /dev/null; then
  eww daemon &
fi

exec dwm
