#!/bin/bash

# colors
fg=#b6beca
bg=#101419
contrast=#15191e
lighter=#1a1e23

black=#242931
red=#e05f65
green=#76b97f
yellow=#f1cf8a
blue=#70a5eb
magenta="#c68aee"
cyan="#74bee9"
white="#dee1e6"

# src
percentage () {
  local val=$(echo $1 | tr '%' ' ' | awk '{print $1}')
  local icon1=$2
  local icon2=$3
  local icon3=$4
  local icon4=$5
  if [ "$val" -le 15 ]; then
    echo $icon1
  elif [ "$val" -le 30 ]; then
    echo $icon2
  elif [ "$val" -le 60 ]; then
    echo $icon3
  else
    echo $icon4
  fi
}

get_network_icon () {
  [ $(cat /sys/class/net/w*/operstate) = down ] && echo 睊 && exit
  echo 
}

get_network () {
  id=$(iwgetid -r || echo "Disconnected")
  icon=$(get_network_icon)
  if [[ $id == "Disconnected" ]]; then
    printf "^b$red^^c$bg^ $icon  ^b$bg^^c$red^  $id  ^b$bg^"
  else
    printf "^b$blue^^c$bg^ $icon  ^b$bg^^c$cyan^  $id  ^b$bg^"
  fi
}

get_volume_icon () {
  local vol=$1
  echo $(percentage "$vol" "" "" "墳" "")
}

get_volume () {
  vol=$(amixer get Master |grep % |awk '{print $5}'|sed -e 's/\[//' -e 's/\]//' | head -n 1)
  icon=$(get_volume_icon $vol)
  vol=$(echo $vol | tr "%" " ")
  vol=$(echo "${vol% }")
  printf "^b$green^^c$bg^ $icon  ^c$green^^b$bg^  $vol%%  "
}

get_vpn () {
  ip=$(ifconfig tun0 2>/dev/null | grep inet | head -n 1 | awk '{print $2}')
  if [[ $ip == "" ]]; then
    echo "^c$magenta^^b$lighter^   ^b$bg^^c$magenta^  Disconnected  ^b$bg^^c$fg^"
  else
    echo "^c$cyan^^b$lighter^   ^b$bg^^c$cyan^  $ip  ^b$bg^^c$fg^"
  fi
}

get_date () {
  printf "^c$magenta^^b$lighter^   ^b$bg^  $(date +'%R')  ^c$fg^^b$bg^"
}

get_ram () {
  printf "^b$lighter^^c$red^   ^b$bg^^c$red^  %.0f%%  ^b$bg^^c$fg^\n" $(free -m | grep Mem | awk '{print ($3/$2)*100}')
}

get_brightness () {
  br=$(light -G | tr '.' ' ' | awk '{print $1}')
  icon=$(percentage "$br" "" "" "" "")
  printf "^c$yellow^ $icon ^b$bg^^c$yellow^ $br%%  ^c$fg^^b$bg^"
}

get_title () {
  # using "  " to get more margin in the bar (problems at patch, and idk how to really fix it lmao)
  echo "$(get_ram)$(get_brightness)$(get_vpn)$(get_network)$(get_date)   "
}

while :; do
  xsetroot -name "$(get_title)"
  sleep 0.5
done &

